#!/usr/bin/env python3
"""Generate the physec OCSF extension (v0.1 sketch)."""
import json, os, shutil

# Regenerates the schema JSON in place, next to this script. Only the
# generated subdirectories are cleared — README, examples, and LICENSE
# live alongside and are never touched.
ROOT = os.path.dirname(os.path.abspath(__file__))
for d in ["events", "objects", "profiles"]:
    p = os.path.join(ROOT, d)
    if os.path.exists(p):
        shutil.rmtree(p)
    os.makedirs(p)


def w(path, obj):
    # newline="\n": output is LF on every platform, so regeneration never
    # produces line-ending diffs against the committed files.
    with open(os.path.join(ROOT, path), "w", newline="\n") as f:
        json.dump(obj, f, indent=2)
        f.write("\n")


def enum(pairs):
    """pairs: list of (id, caption, description)"""
    return {str(i): {"caption": c, "description": d} for i, c, d in pairs}


# ---------------------------------------------------------------- extension
w("extension.json", {
    "uid": 42,
    "caption": "Physical Security",
    "description": "The Physical Security extension defines event classes and objects for physical security operations, covering access control, alarm signalling and disposition, guard patrols, post staffing, response dispatch, and incident reporting. Event identifiers are crosswalked to established vocabularies including the SIA DC-03 format, the Ademco Contact ID protocol, ONVIF topic namespaces, and the ANSI/TMA AVS-01 alarm validation score.",
    "name": "physec",
    "version": "0.1.0",
})

w("categories.json", {
    "caption": "Categories",
    "description": "Categories defined by the Physical Security extension.",
    "name": "category",
    "attributes": {
        "physical_security": {
            "uid": 30,
            "caption": "Physical Security",
            "description": "Physical Security events report activity in the physical world, including access control decisions, alarm signals and their disposition, guard patrols, post staffing, response resource dispatch, and incident reports.",
        }
    },
})

# ---------------------------------------------------------------- dictionary
LIFECYCLE = enum([
    (1, "New", "A new event condition, equivalent to Contact ID qualifier 1."),
    (2, "Restore", "The condition returned to normal, equivalent to Contact ID qualifier 3 and the SIA DC-03 second-letter modifier R."),
    (3, "Still Present", "A previously reported condition is still present, equivalent to Contact ID qualifier 6."),
    (4, "Cancel", "The condition was cancelled by an authorized person."),
    (5, "Trouble", "A fault condition affecting the point or device."),
    (6, "Trouble Restore", "A fault condition returned to normal."),
    (7, "Bypass", "The point was bypassed or shunted."),
    (8, "Unbypass", "The point was returned to service."),
    (9, "Test", "The event was generated by a test."),
])

URGENCY = enum([
    (1, "Immediate", "Responsive action should be taken immediately."),
    (2, "Expected", "Responsive action should be taken soon."),
    (3, "Future", "Responsive action should be taken in the near future."),
    (4, "Past", "Responsive action is no longer required."),
])

CERTAINTY = enum([
    (1, "Observed", "Determined to have occurred or to be ongoing."),
    (2, "Likely", "Probability greater than approximately 50 percent."),
    (3, "Possible", "Probability less than or equal to approximately 50 percent."),
    (4, "Unlikely", "Not expected to occur, with probability approaching zero."),
])

RESPONSE_TYPE = enum([
    (1, "Shelter", "Take shelter in place."),
    (2, "Evacuate", "Relocate as instructed."),
    (3, "Prepare", "Make preparations."),
    (4, "Execute", "Execute a pre-planned activity."),
    (5, "Avoid", "Avoid the subject area."),
    (6, "Monitor", "Attend to information sources."),
    (7, "Assess", "Evaluate the information in this event."),
    (8, "All Clear", "The subject event no longer poses a threat."),
    (9, "None", "No action recommended."),
])

VALIDATION_LEVEL = enum([
    (1, "Level 0", "No call for service. Response is unwarranted, as defined by ANSI/TMA AVS-01."),
    (2, "Level 1", "A call for service with no other information. The default level absent contributing factors."),
    (3, "Level 2", "A call for service with proof of, or high probability of, a person present at the site."),
    (4, "Level 3", "A call for service with a person present and an apparent threat to property."),
    (5, "Level 4", "A call for service with a person present and an apparent threat to life."),
])

VERIFICATION_METHOD = enum([
    (1, "None", "No verification was attempted."),
    (2, "Phone Confirmation", "A single confirmation call was placed."),
    (3, "Enhanced Confirmation", "Two or more investigative calls were placed, as defined by ANSI/TMA CS-V-01."),
    (4, "Two Way Audio", "An event-driven hands-free audio session was used."),
    (5, "Listen In", "A one-way audio session was used."),
    (6, "Video", "Recorded or live video was reviewed by a human operator."),
    (7, "Analytics", "An automated analytic produced the verification determination."),
    (8, "Eyewitness", "A person at the site confirmed the condition."),
    (9, "On Site Check", "A responder physically checked the location."),
])

CAUSE = enum([
    (1, "Genuine", "The condition was real and correctly reported."),
    (2, "User Error", "An authorized person triggered the condition in error."),
    (3, "Equipment Malfunction", "The detection device or panel malfunctioned."),
    (4, "Equipment Unsuitable", "The device was inappropriate for the environment."),
    (5, "Installation Fault", "The device was incorrectly installed or aimed."),
    (6, "Environmental", "Weather, lighting, foliage, or similar environmental conditions."),
    (7, "Animal", "An animal triggered the condition."),
    (8, "Authorized Activity", "A scheduled or permitted activity triggered the condition."),
    (9, "Communication Fault", "A transmission or network fault produced the signal."),
    (10, "Monitoring Error", "The monitoring centre processed the signal incorrectly."),
    (11, "Malicious", "The condition was triggered deliberately and without cause."),
])

DISPATCH_OUTCOME = enum([
    (1, "No Dispatch", "No response resource was dispatched."),
    (2, "Dispatched", "A response resource was dispatched."),
    (3, "Cancelled En Route", "A dispatch was cancelled before arrival."),
    (4, "Responded Verified", "A resource arrived and confirmed the condition."),
    (5, "Responded Unfounded", "A resource arrived and found no condition."),
    (6, "Chargeable False Alarm", "The event was assessed as a chargeable false alarm under a local ordinance."),
])

DERIVATION = enum([
    (1, "Direct", "Reported directly by a device or person."),
    (2, "Sensor Fusion", "Inferred by correlating two or more sensor sources."),
    (3, "Video Analytic", "Inferred by a video analytic."),
    (4, "Count Reconciliation", "Inferred by reconciling grant counts against door contact transitions."),
    (5, "Schedule Correlation", "Inferred by correlating against an expected schedule."),
    (6, "Human Assessment", "Determined by a human operator."),
])

w("dictionary.json", {
    "caption": "Attribute Dictionary",
    "description": "Attributes defined by the Physical Security extension.",
    "name": "dictionary",
    "attributes": {
        # --- shared classification axes -------------------------------
        "lifecycle_id": {"caption": "Lifecycle ID", "description": "The normalized lifecycle state of the condition, separating the state transition from the event type. This mirrors the SIA DC-03 second-letter modifier and the Contact ID qualifier field.", "type": "integer_t", "enum": LIFECYCLE, "sibling": "lifecycle"},
        "lifecycle": {"caption": "Lifecycle", "description": "The lifecycle state, normalized to the caption of the <code>lifecycle_id</code> value.", "type": "string_t"},
        "urgency_id": {"caption": "Urgency ID", "description": "The time available to take responsive action, using the dimension defined by the Common Alerting Protocol.", "type": "integer_t", "enum": URGENCY, "sibling": "urgency"},
        "urgency": {"caption": "Urgency", "description": "The urgency, normalized to the caption of the <code>urgency_id</code> value.", "type": "string_t"},
        "certainty_id": {"caption": "Certainty ID", "description": "The confidence that the reported condition occurred, using the dimension defined by the Common Alerting Protocol.", "type": "integer_t", "enum": CERTAINTY, "sibling": "certainty"},
        "certainty": {"caption": "Certainty", "description": "The certainty, normalized to the caption of the <code>certainty_id</code> value.", "type": "string_t"},
        "response_type_id": {"caption": "Response Type ID", "description": "The recommended responsive action, using the dimension defined by the Common Alerting Protocol.", "type": "integer_t", "enum": RESPONSE_TYPE, "sibling": "response_type"},
        "response_type": {"caption": "Response Type", "description": "The response type, normalized to the caption of the <code>response_type_id</code> value.", "type": "string_t"},
        "derivation_id": {"caption": "Derivation ID", "description": "How the reported condition was determined. Inferred conditions such as tailgating are not directly observable and must declare their derivation.", "type": "integer_t", "enum": DERIVATION, "sibling": "derivation"},
        "derivation": {"caption": "Derivation", "description": "The derivation method, normalized to the caption of the <code>derivation_id</code> value.", "type": "string_t"},
        "confidence_pct": {"caption": "Confidence Percentage", "description": "The confidence of an inferred determination, expressed as a percentage from 0 to 100.", "type": "integer_t"},

        # --- crosswalk ------------------------------------------------
        "signal_code": {"caption": "Signal Code", "description": "The equivalent identifiers for this event in established physical security vocabularies.", "type": "signal_code"},
        "sia_dc03_code": {"caption": "SIA DC-03 Code", "description": "The two-character event code defined by the SIA DC-03 format standard.", "type": "string_t"},
        "contact_id_code": {"caption": "Contact ID Code", "description": "The three-digit event code defined by the Ademco Contact ID protocol.", "type": "string_t"},
        "contact_id_qualifier": {"caption": "Contact ID Qualifier", "description": "The Contact ID qualifier, where 1 indicates a new event, 3 a restore, and 6 a previously reported condition still present.", "type": "string_t"},
        "onvif_topic": {"caption": "ONVIF Topic", "description": "The ONVIF topic namespace string for this event.", "type": "string_t"},
        "osdp_reply": {"caption": "OSDP Reply", "description": "The OSDP reply name from which this event was derived.", "type": "string_t"},
        "native_type": {"caption": "Native Type", "description": "The event type string as emitted by the originating system, retained verbatim.", "type": "string_t"},

        # --- objects --------------------------------------------------
        "portal": {"caption": "Portal", "description": "The door, gate, turnstile, or other controlled opening.", "type": "portal"},
        "credential": {"caption": "Credential", "description": "The credential presented.", "type": "credential"},
        "zone": {"caption": "Zone", "description": "The security zone or area.", "type": "zone"},
        "alarm_point": {"caption": "Alarm Point", "description": "The monitored point that generated the signal.", "type": "alarm_point"},
        "post": {"caption": "Post", "description": "The guard post.", "type": "post"},
        "checkpoint": {"caption": "Checkpoint", "description": "The patrol checkpoint.", "type": "checkpoint"},
        "patrol_tour": {"caption": "Patrol Tour", "description": "The patrol tour session.", "type": "patrol_tour"},
        "response_resource": {"caption": "Response Resource", "description": "The resource assigned to respond.", "type": "response_resource", "is_array": True},
        "disposition": {"caption": "Disposition", "description": "The validated outcome of the signal.", "type": "disposition"},

        # --- portal ---------------------------------------------------
        "portal_type_id": {"caption": "Portal Type ID", "description": "The normalized type of the controlled opening.", "type": "integer_t", "sibling": "portal_type", "enum": enum([
            (1, "Door", "A pedestrian door."),
            (2, "Gate", "A vehicle or pedestrian gate."),
            (3, "Turnstile", "A turnstile or speed lane."),
            (4, "Mantrap", "An interlocked pair of portals."),
            (5, "Barrier", "A vehicle barrier or bollard."),
            (6, "Elevator", "An elevator or floor-access control point."),
            (7, "Cage", "A cabinet, cage, or rack door."),
        ])},
        "portal_type": {"caption": "Portal Type", "description": "The portal type, normalized to the caption of the <code>portal_type_id</code> value.", "type": "string_t"},
        "portal_mode": {"caption": "Portal Mode", "description": "The commanded state of the portal, using the ONVIF door mode vocabulary. Expected values are Locked, Unlocked, Accessed, Blocked, LockedDown, LockedOpen, and DoubleLocked.", "type": "string_t"},
        "portal_physical_state": {"caption": "Portal Physical State", "description": "The observed physical state of the portal, using the ONVIF vocabulary. Expected values are Open, Closed, and Fault.", "type": "string_t"},
        "held_open_duration": {"caption": "Held Open Duration", "description": "The time in milliseconds the portal remained open beyond its configured threshold.", "type": "integer_t"},

        # --- credential -----------------------------------------------
        "credential_type_id": {"caption": "Credential Type ID", "description": "The normalized form of the credential presented.", "type": "integer_t", "sibling": "credential_type", "enum": enum([
            (1, "Card", "A physical proximity or smart card."),
            (2, "Mobile", "A mobile device credential."),
            (3, "PIN", "A keypad-entered personal identification number."),
            (4, "Biometric", "A biometric sample."),
            (5, "License Plate", "A vehicle registration plate read."),
            (6, "Key", "A mechanical key."),
            (7, "Escort", "Entry authorized by an escorting person rather than by a credential."),
        ])},
        "credential_type": {"caption": "Credential Type", "description": "The credential type, normalized to the caption of the <code>credential_type_id</code> value.", "type": "string_t"},
        "credential_status": {"caption": "Credential Status", "description": "The status of the credential, using the ONVIF credential reason vocabulary. Expected values are LockedOut, Blocked, Lost, Stolen, Damaged, Destroyed, Inactivity, Expired, and RenewalNeeded.", "type": "string_t"},
        "is_antipassback_violated": {"caption": "Antipassback Violated", "description": "Indicates the presentation violated an antipassback rule.", "type": "boolean_t"},

        # --- zone / alarm point ---------------------------------------
        "zone_type_id": {"caption": "Zone Type ID", "description": "The normalized classification of the zone.", "type": "integer_t", "sibling": "zone_type", "enum": enum([
            (1, "Perimeter", "The outer boundary of the site."),
            (2, "Public", "An area open to the public."),
            (3, "Restricted", "An area restricted to authorized persons."),
            (4, "Critical", "An area containing critical assets."),
            (5, "Transitional", "A lobby, corridor, or other transitional space."),
            (6, "External", "An outdoor area within the site boundary."),
        ])},
        "zone_type": {"caption": "Zone Type", "description": "The zone type, normalized to the caption of the <code>zone_type_id</code> value.", "type": "string_t"},
        "is_armed": {"caption": "Armed", "description": "Indicates the zone or point was armed at the time of the event.", "type": "boolean_t"},
        "sensor_type": {"caption": "Sensor Type", "description": "The detection technology of the monitored point, for example contact, motion, glassbreak, seismic, beam, fence, radar, or lidar.", "type": "string_t"},

        # --- post / patrol --------------------------------------------
        "post_type_id": {"caption": "Post Type ID", "description": "The normalized type of guard post.", "type": "integer_t", "sibling": "post_type", "enum": enum([
            (1, "Fixed", "A static post at a defined location."),
            (2, "Patrol", "A roving post covering an area."),
            (3, "Gatehouse", "An access-control post at a vehicle or pedestrian entrance."),
            (4, "Console", "A monitoring position in an operations centre."),
            (5, "Mobile", "A vehicle-based post covering multiple sites."),
            (6, "Remote", "A post staffed from a remote operations centre."),
        ])},
        "post_type": {"caption": "Post Type", "description": "The post type, normalized to the caption of the <code>post_type_id</code> value.", "type": "string_t"},
        "is_billable": {"caption": "Billable", "description": "Indicates the hours associated with this event are billable to the client.", "type": "boolean_t"},
        "scheduled_start_time": {"caption": "Scheduled Start Time", "description": "The scheduled start time of the shift or tour.", "type": "timestamp_t"},
        "scheduled_end_time": {"caption": "Scheduled End Time", "description": "The scheduled end time of the shift or tour.", "type": "timestamp_t"},
        "variance": {"caption": "Variance", "description": "The signed difference in milliseconds between the scheduled and actual time. A positive value indicates the actual time was later than scheduled.", "type": "integer_t"},
        "checkpoint_token_type": {"caption": "Checkpoint Token Type", "description": "The physical token technology used to register a checkpoint scan, for example NFC, QR, iButton, BLE, or GPS.", "type": "string_t"},
        "checkpoint_count": {"caption": "Checkpoint Count", "description": "The number of checkpoints registered during the tour.", "type": "integer_t"},
        "checkpoint_expected_count": {"caption": "Expected Checkpoint Count", "description": "The number of checkpoints the tour was expected to register.", "type": "integer_t"},
        "is_out_of_sequence": {"caption": "Out Of Sequence", "description": "Indicates the checkpoint was registered outside its expected order.", "type": "boolean_t"},
        "geofence_status": {"caption": "Geofence Status", "description": "Whether the reported position fell inside or outside the defined geofence at the time of the event.", "type": "string_t"},
        "position_accuracy": {"caption": "Position Accuracy", "description": "The horizontal accuracy of the reported position, in metres.", "type": "integer_t"},

        # --- response --------------------------------------------------
        "resource_type_id": {"caption": "Resource Type ID", "description": "The normalized type of response resource.", "type": "integer_t", "sibling": "resource_type", "enum": enum([
            (1, "On Site Officer", "An officer already posted at the site."),
            (2, "Mobile Patrol", "A vehicle-based officer covering multiple sites."),
            (3, "Remote Operator", "A human operator in a remote monitoring centre."),
            (4, "Automated Talkdown", "An automated voice-down over a speaker."),
            (5, "Drone", "An uncrewed aerial system."),
            (6, "Ground Robot", "An uncrewed ground vehicle."),
            (7, "Law Enforcement", "A public law enforcement agency."),
            (8, "Fire Or EMS", "A public fire or emergency medical service."),
            (9, "Client Contact", "A representative of the client organization."),
        ])},
        "resource_type": {"caption": "Resource Type", "description": "The resource type, normalized to the caption of the <code>resource_type_id</code> value.", "type": "string_t"},
        "assigned_time": {"caption": "Assigned Time", "description": "The time the resource was assigned to the event.", "type": "timestamp_t"},
        "enroute_time": {"caption": "En Route Time", "description": "The time the resource began travelling to the location.", "type": "timestamp_t"},
        "on_scene_time": {"caption": "On Scene Time", "description": "The time the resource arrived at the location.", "type": "timestamp_t"},
        "cleared_time": {"caption": "Cleared Time", "description": "The time the resource was released from the event.", "type": "timestamp_t"},
        "time_to_triage": {"caption": "Time To Triage", "description": "The elapsed time in milliseconds from signal receipt to a disposition being assigned.", "type": "integer_t"},
        "time_to_resolution": {"caption": "Time To Resolution", "description": "The elapsed time in milliseconds from signal receipt to the event being closed.", "type": "integer_t"},

        # --- disposition ------------------------------------------------
        "validation_level_id": {"caption": "Validation Level ID", "description": "The alarm validation score defined by ANSI/TMA AVS-01.", "type": "integer_t", "sibling": "validation_level", "enum": VALIDATION_LEVEL},
        "validation_level": {"caption": "Validation Level", "description": "The validation level, normalized to the caption of the <code>validation_level_id</code> value.", "type": "string_t"},
        "verification_method_id": {"caption": "Verification Method ID", "description": "The method used to verify or confirm the condition, drawing on ANSI/TMA CS-V-01.", "type": "integer_t", "sibling": "verification_method", "enum": VERIFICATION_METHOD},
        "verification_method": {"caption": "Verification Method", "description": "The verification method, normalized to the caption of the <code>verification_method_id</code> value.", "type": "string_t"},
        "cause_id": {"caption": "Cause ID", "description": "The assessed cause of the signal.", "type": "integer_t", "sibling": "cause", "enum": CAUSE},
        "cause": {"caption": "Cause", "description": "The cause, normalized to the caption of the <code>cause_id</code> value.", "type": "string_t"},
        "dispatch_outcome_id": {"caption": "Dispatch Outcome ID", "description": "What ultimately happened in response to the signal.", "type": "integer_t", "sibling": "dispatch_outcome", "enum": DISPATCH_OUTCOME},
        "dispatch_outcome": {"caption": "Dispatch Outcome", "description": "The dispatch outcome, normalized to the caption of the <code>dispatch_outcome_id</code> value.", "type": "string_t"},

        # --- incident ---------------------------------------------------
        "incident_type_common": {"caption": "Common Incident Type", "description": "The incident type drawn from the controlled vocabulary published by this extension. Required so that locally defined types remain comparable across organizations.", "type": "string_t"},
        "incident_type_internal": {"caption": "Internal Incident Type", "description": "The incident type as classified by the reporting organization, retained verbatim.", "type": "string_t"},
        "nibrs_offense_code": {"caption": "NIBRS Offense Code", "description": "The offense code from the National Incident-Based Reporting System, where the incident describes a criminal act.", "type": "string_t"},
        "apco_incident_type": {"caption": "APCO Incident Type", "description": "The common incident type code used for public safety data exchange, where the incident was referred for dispatch.", "type": "string_t"},
        "narrative": {"caption": "Narrative", "description": "The free-text account of the incident recorded by the reporting person.", "type": "string_t"},
        "is_reportable": {"caption": "Reportable", "description": "Indicates the incident meets a client or regulatory reporting threshold.", "type": "boolean_t"},
        "loss_amount": {"caption": "Loss Amount", "description": "The estimated financial loss associated with the incident, in the smallest unit of the reporting currency.", "type": "long_t"},

        # --- site context (profile) ---------------------------------------
        "site_uid": {"caption": "Site UID", "description": "The unique identifier of the physical site.", "type": "string_t"},
        "site_name": {"caption": "Site Name", "description": "The name of the physical site.", "type": "string_t"},
        "building": {"caption": "Building", "description": "The building within the site.", "type": "string_t"},
        "floor": {"caption": "Floor", "description": "The floor or level within the building.", "type": "string_t"},
    },
})

# ---------------------------------------------------------------- profile
w("profiles/physical_site.json", {
    "caption": "Physical Site",
    "description": "The Physical Site profile adds physical location context to any event class. Applying it to core Identity and Access Management or Authentication classes allows logical access events to be correlated with physical presence at the same site.",
    "meta": "profile",
    "name": "physical_site",
    "attributes": {
        "site_uid": {"requirement": "recommended"},
        "site_name": {"requirement": "optional"},
        "building": {"requirement": "optional"},
        "floor": {"requirement": "optional"},
        "zone": {"requirement": "optional"},
    },
})

# ---------------------------------------------------------------- objects
w("objects/signal_code.json", {
    "caption": "Signal Code",
    "description": "The Signal Code object carries the equivalent identifiers for an event in established physical security vocabularies. Populating it allows a normalized event to be traced back to the code the originating system actually transmitted, and allows consumers to match on a vocabulary they already support.",
    "extends": "object",
    "name": "signal_code",
    "attributes": {
        "sia_dc03_code": {"requirement": "optional"},
        "contact_id_code": {"requirement": "optional"},
        "contact_id_qualifier": {"requirement": "optional"},
        "onvif_topic": {"requirement": "optional"},
        "osdp_reply": {"requirement": "optional"},
        "native_type": {"requirement": "recommended"},
    },
    "constraints": {"at_least_one": ["sia_dc03_code", "contact_id_code", "onvif_topic", "osdp_reply", "native_type"]},
})

w("objects/portal.json", {
    "caption": "Portal",
    "description": "The Portal object describes a controlled opening such as a door, gate, turnstile, or barrier, together with its commanded and observed state.",
    "extends": "_entity",
    "name": "portal",
    "observable": 42001,
    "attributes": {
        "portal_type_id": {"group": "classification", "requirement": "required"},
        "portal_type": {"requirement": "optional"},
        "portal_mode": {"requirement": "recommended"},
        "portal_physical_state": {"requirement": "recommended"},
        "zone": {"requirement": "recommended"},
        "location": {"requirement": "optional"},
    },
})

w("objects/credential.json", {
    "caption": "Credential",
    "description": "The Credential object describes a token presented to obtain access. Identifying values are expected to be tokenized or hashed by the producer; raw biometric samples are out of scope for this schema and must not be carried.",
    "extends": "_entity",
    "name": "credential",
    "observable": 42002,
    "attributes": {
        "credential_type_id": {"group": "classification", "requirement": "required"},
        "credential_type": {"requirement": "optional"},
        "credential_status": {"requirement": "optional"},
        "is_antipassback_violated": {"requirement": "optional"},
        "user": {"requirement": "recommended"},
    },
})

w("objects/zone.json", {
    "caption": "Zone",
    "description": "The Zone object describes a security zone or area within a site.",
    "extends": "_entity",
    "name": "zone",
    "observable": 42003,
    "attributes": {
        "zone_type_id": {"group": "classification", "requirement": "recommended"},
        "zone_type": {"requirement": "optional"},
        "is_armed": {"requirement": "optional"},
        "location": {"requirement": "optional"},
    },
})

w("objects/alarm_point.json", {
    "caption": "Alarm Point",
    "description": "The Alarm Point object describes a monitored detection point, such as a contact, motion sensor, or beam, and the panel or device that supervises it.",
    "extends": "_entity",
    "name": "alarm_point",
    "observable": 42004,
    "attributes": {
        "sensor_type": {"requirement": "recommended"},
        "is_armed": {"requirement": "recommended"},
        "zone": {"requirement": "recommended"},
        "device": {"requirement": "optional"},
    },
})

w("objects/post.json", {
    "caption": "Post",
    "description": "The Post object describes a guard post: a defined staffing position at a site with an associated coverage requirement.",
    "extends": "_entity",
    "name": "post",
    "observable": 42005,
    "attributes": {
        "post_type_id": {"group": "classification", "requirement": "required"},
        "post_type": {"requirement": "optional"},
        "zone": {"requirement": "optional"},
        "location": {"requirement": "optional"},
    },
})

w("objects/checkpoint.json", {
    "caption": "Checkpoint",
    "description": "The Checkpoint object describes a location a patrol is expected to visit and register, together with the token technology used to prove presence.",
    "extends": "_entity",
    "name": "checkpoint",
    "observable": 42006,
    "attributes": {
        "checkpoint_token_type": {"requirement": "recommended"},
        "zone": {"requirement": "optional"},
        "location": {"requirement": "recommended"},
    },
})

w("objects/patrol_tour.json", {
    "caption": "Patrol Tour",
    "description": "The Patrol Tour object describes a defined patrol route and the schedule against which its completion is measured.",
    "extends": "_entity",
    "name": "patrol_tour",
    "observable": 42007,
    "attributes": {
        "checkpoint_expected_count": {"requirement": "recommended"},
        "scheduled_start_time": {"requirement": "optional"},
        "scheduled_end_time": {"requirement": "optional"},
    },
})

w("objects/response_resource.json", {
    "caption": "Response Resource",
    "description": "The Response Resource object describes a resource assigned to act on an event, together with the timestamps that define its response interval. Human, remote, robotic, and public-agency resources are represented uniformly so that response paths can be compared.",
    "extends": "_entity",
    "name": "response_resource",
    "observable": 42008,
    "attributes": {
        "resource_type_id": {"group": "classification", "requirement": "required"},
        "resource_type": {"requirement": "optional"},
        "user": {"requirement": "optional"},
        "device": {"requirement": "optional"},
        "assigned_time": {"requirement": "recommended"},
        "enroute_time": {"requirement": "optional"},
        "on_scene_time": {"requirement": "optional"},
        "cleared_time": {"requirement": "optional"},
    },
})

w("objects/disposition.json", {
    "caption": "Disposition",
    "description": "The Disposition object records what an event turned out to be and what was done about it. It is the link between a reported signal and its verified outcome, and is what allows false alarm rates, verification effectiveness, and response performance to be measured across sites and systems.",
    "extends": "object",
    "name": "disposition",
    "attributes": {
        "validation_level_id": {"group": "classification", "requirement": "required"},
        "validation_level": {"requirement": "optional"},
        "verification_method_id": {"group": "classification", "requirement": "recommended"},
        "verification_method": {"requirement": "optional"},
        "cause_id": {"group": "classification", "requirement": "recommended"},
        "cause": {"requirement": "optional"},
        "dispatch_outcome_id": {"group": "classification", "requirement": "recommended"},
        "dispatch_outcome": {"requirement": "optional"},
        "time_to_triage": {"requirement": "recommended"},
        "time_to_resolution": {"requirement": "optional"},
    },
})

# patch core location
w("objects/location.json", {
    "caption": "Geo Location",
    "description": "Adds physical site context to the core Geo Location object.",
    "extends": "location",
    "attributes": {
        "site_uid": {"requirement": "optional"},
        "site_name": {"requirement": "optional"},
        "building": {"requirement": "optional"},
        "floor": {"requirement": "optional"},
    },
})

# ---------------------------------------------------------------- events
CAT = "physical_security"

# hidden base class
w("events/physical_security.json", {
    "caption": "Physical Security",
    "category": CAT,
    "description": "Physical Security events report activity in the physical world. This is the base event class from which all Physical Security classes derive; it is not used directly.",
    "extends": "base_event",
    "name": "physical_security",
    "profiles": ["physical_site"],
    "attributes": {
        "lifecycle_id": {"group": "classification", "requirement": "recommended"},
        "lifecycle": {"requirement": "optional"},
        "signal_code": {"group": "context", "requirement": "recommended"},
        "derivation_id": {"group": "classification", "requirement": "recommended"},
        "derivation": {"requirement": "optional"},
        "confidence_pct": {"requirement": "optional"},
        "urgency_id": {"requirement": "optional"},
        "urgency": {"requirement": "optional"},
        "certainty_id": {"requirement": "optional"},
        "certainty": {"requirement": "optional"},
        "response_type_id": {"requirement": "optional"},
        "response_type": {"requirement": "optional"},
        "zone": {"group": "context", "requirement": "recommended"},
        "location": {"group": "context", "requirement": "recommended"},
        "device": {"group": "context", "requirement": "optional"},
        "actor": {"group": "context", "requirement": "optional"},
    },
})

w("events/physical_access_activity.json", {
    "uid": 1,
    "caption": "Physical Access Activity",
    "category": CAT,
    "description": "Physical Access Activity events report access control decisions and portal state changes. The activity set follows the ONVIF Access Control and Door Control service vocabularies, which separate the access decision from whether the portal was actually used. That separation is what makes tailgating and no-entry-made conditions expressible.",
    "extends": "physical_security",
    "name": "physical_access_activity",
    "attributes": {
        "activity_id": {"enum": enum([
            (1, "Access Granted", "Access was authorized. Equivalent to ONVIF AccessGranted, SIA DG, and Contact ID 422."),
            (2, "Access Denied", "Access was refused. Equivalent to ONVIF Denied, SIA DD or DK, and Contact ID 421."),
            (3, "Access Taken", "Access was authorized and the portal was used. Equivalent to ONVIF AccessTaken."),
            (4, "Access Not Taken", "Access was authorized but the portal was not used. Equivalent to ONVIF AccessNotTaken."),
            (5, "Portal Forced", "The portal was opened without an access request. Equivalent to ONVIF DoorForcedOpen, SIA DF, and Contact ID 423."),
            (6, "Portal Held Open", "The portal remained open beyond its configured threshold. Equivalent to ONVIF DoorOpenTooLong, SIA DN, and Contact ID 426."),
            (7, "Request To Exit", "An egress request was registered. Equivalent to SIA DX and Contact ID 425."),
            (8, "Duress", "A duress credential or code was presented. Equivalent to ONVIF Duress, SIA HA, and Contact ID 121 or 434."),
            (9, "Antipassback Violation", "The presentation violated an antipassback rule. Equivalent to SIA DI."),
            (10, "Tailgate", "More persons transited than were authorized. This condition is not directly observable and is always inferred; the derivation attribute is required."),
            (11, "Portal Mode Changed", "The commanded state of the portal changed."),
            (12, "Tamper", "The portal, reader, or its enclosure was tampered with. Equivalent to SIA TA and Contact ID 137 or 144."),
        ])},
        "portal": {"group": "primary", "requirement": "required"},
        "credential": {"group": "primary", "requirement": "recommended"},
        "held_open_duration": {"requirement": "optional"},
    },
    "constraints": {"at_least_one": ["portal", "credential"]},
})

w("events/alarm_signal_activity.json", {
    "uid": 2,
    "caption": "Alarm Signal Activity",
    "category": CAT,
    "description": "Alarm Signal Activity events report signals received from intrusion, environmental, and supervisory detection points. The event type describes what kind of condition was reported; the lifecycle attribute inherited from the base class describes the state transition, mirroring the modifier letter in the SIA DC-03 format and the qualifier field in the Ademco Contact ID protocol. Restore and trouble conditions are therefore not separate activities.",
    "extends": "physical_security",
    "name": "alarm_signal_activity",
    "attributes": {
        "activity_id": {"enum": enum([
            (1, "Intrusion", "An intrusion detection point was activated. Equivalent to SIA BA and Contact ID 130."),
            (2, "Perimeter", "A perimeter detection point was activated. Equivalent to Contact ID 131."),
            (3, "Holdup", "A holdup or silent alarm was activated. Equivalent to SIA HA and Contact ID 122."),
            (4, "Panic", "A panic alarm was manually activated. Equivalent to SIA PA and Contact ID 120."),
            (5, "Tamper", "Detection equipment or its enclosure was tampered with. Equivalent to SIA TA and Contact ID 137."),
            (6, "Environmental", "An environmental condition such as water, gas, or temperature was detected."),
            (7, "Supervisory", "A supervisory condition such as power or battery was reported. Equivalent to SIA AT or YT and Contact ID 201 or 302."),
            (8, "Communication", "A communication path fault was reported. Equivalent to SIA YC and Contact ID 350."),
            (9, "Opening", "The zone or partition was disarmed. Equivalent to SIA OP and Contact ID 400."),
            (10, "Closing", "The zone or partition was armed. Equivalent to SIA CL and Contact ID 400."),
            (11, "Video Analytic", "A video analytic rule was triggered. Equivalent to an ONVIF RuleEngine topic."),
        ])},
        "alarm_point": {"group": "primary", "requirement": "required"},
    },
})

w("events/alarm_disposition_activity.json", {
    "uid": 3,
    "caption": "Alarm Disposition Activity",
    "category": CAT,
    "description": "Alarm Disposition Activity events report what a signal turned out to be after triage. This is the class that converts raw signals into measurable outcomes: it records the validation level assigned, the method used to reach it, the assessed cause, and what was ultimately dispatched. Emitting a disposition for every signal is what makes false alarm rates, verification effectiveness, and triage latency comparable across sites, systems, and vendors.",
    "extends": "physical_security",
    "name": "alarm_disposition_activity",
    "attributes": {
        "activity_id": {"enum": enum([
            (1, "Triaged", "A disposition was assigned to the signal."),
            (2, "Escalated", "The signal was escalated for further assessment or response."),
            (3, "Cleared", "The signal was closed without further action."),
            (4, "Reopened", "A previously closed signal was reopened."),
        ])},
        "disposition": {"group": "primary", "requirement": "required"},
        "alarm_point": {"group": "primary", "requirement": "recommended"},
        "response_resource": {"requirement": "optional"},
    },
})

w("events/patrol_activity.json", {
    "uid": 4,
    "caption": "Patrol Activity",
    "category": CAT,
    "description": "Patrol Activity events report the execution of guard patrols against their defined routes and schedules. No published standard covers this area; the model here follows the widely used pattern of a tour definition, an occurrence of that tour, and the checkpoint registrations and exceptions recorded within it.",
    "extends": "physical_security",
    "name": "patrol_activity",
    "attributes": {
        "activity_id": {"enum": enum([
            (1, "Tour Started", "A patrol tour began."),
            (2, "Checkpoint Registered", "A checkpoint was registered by the officer on patrol."),
            (3, "Tour Completed", "A patrol tour finished with all expected checkpoints registered."),
            (4, "Tour Incomplete", "A patrol tour finished with fewer checkpoints registered than expected."),
            (5, "Tour Missed", "A scheduled patrol tour did not start."),
            (6, "Checkpoint Missed", "An expected checkpoint was not registered."),
            (7, "Tour Overrun", "A patrol tour exceeded its expected duration."),
            (8, "Geofence Exception", "A checkpoint was registered from outside the defined geofence."),
            (9, "Sequence Exception", "A checkpoint was registered outside its expected order."),
        ])},
        "patrol_tour": {"group": "primary", "requirement": "required"},
        "checkpoint": {"group": "primary", "requirement": "recommended"},
        "post": {"requirement": "optional"},
        "checkpoint_count": {"requirement": "optional"},
        "is_out_of_sequence": {"requirement": "optional"},
        "geofence_status": {"requirement": "optional"},
        "position_accuracy": {"requirement": "optional"},
        "variance": {"requirement": "optional"},
    },
})

w("events/post_staffing_activity.json", {
    "uid": 5,
    "caption": "Post Staffing Activity",
    "category": CAT,
    "description": "Post Staffing Activity events report whether guard posts were staffed as contracted. No published standard covers this area. These events are the record of coverage against obligation, and they are the basis on which the cost and reliability of human posts can be compared against automated alternatives.",
    "extends": "physical_security",
    "name": "post_staffing_activity",
    "attributes": {
        "activity_id": {"enum": enum([
            (1, "Post Assumed", "An officer took over the post."),
            (2, "Post Relieved", "An officer was relieved from the post."),
            (3, "Late Arrival", "An officer assumed the post later than scheduled."),
            (4, "No Show", "No officer assumed the post at the scheduled time."),
            (5, "Post Abandoned", "The post was left unstaffed before the scheduled relief."),
            (6, "Break Started", "A scheduled rest or meal period began."),
            (7, "Break Ended", "A scheduled rest or meal period ended."),
            (8, "Break Missed", "A scheduled rest or meal period was not taken."),
            (9, "Coverage Gap", "The post was unstaffed during a period it was contracted to be staffed."),
            (10, "Overtime Incurred", "Hours were worked beyond the scheduled shift."),
        ])},
        "post": {"group": "primary", "requirement": "required"},
        "scheduled_start_time": {"requirement": "recommended"},
        "scheduled_end_time": {"requirement": "optional"},
        "variance": {"requirement": "recommended"},
        "is_billable": {"requirement": "optional"},
    },
})

w("events/response_activity.json", {
    "uid": 6,
    "caption": "Response Activity",
    "category": CAT,
    "description": "Response Activity events report the assignment and progress of resources responding to a condition. Human officers, remote operators, automated talkdown, uncrewed systems, and public agencies are represented uniformly so that the cost, latency, and outcome of different response paths can be compared for the same class of event.",
    "extends": "physical_security",
    "name": "response_activity",
    "attributes": {
        "activity_id": {"enum": enum([
            (1, "Assigned", "A resource was assigned to the event."),
            (2, "Acknowledged", "The assigned resource acknowledged the assignment."),
            (3, "En Route", "The resource began travelling to the location."),
            (4, "On Scene", "The resource arrived at the location."),
            (5, "Action Taken", "The resource performed an intervention such as a talkdown, a challenge, or a lock-down."),
            (6, "Cleared", "The resource was released from the event."),
            (7, "Declined", "The resource was unable to accept the assignment."),
            (8, "Reassigned", "The event was transferred to a different resource."),
            (9, "Escalated To Agency", "The event was referred to a public safety agency."),
        ])},
        "response_resource": {"group": "primary", "requirement": "required"},
        "disposition": {"requirement": "optional"},
        "post": {"requirement": "optional"},
    },
})

w("events/incident_report_activity.json", {
    "uid": 7,
    "caption": "Incident Report Activity",
    "category": CAT,
    "description": "Incident Report Activity events report the lifecycle of a documented incident. Classification follows the dual-coding pattern established by the Emergency Incident Data Document: a required common type drawn from a published controlled vocabulary, alongside the reporting organization's own internal type. Optional crosswalk attributes carry the equivalent public safety and offense codes where the incident maps to them.",
    "extends": "physical_security",
    "name": "incident_report_activity",
    "attributes": {
        "activity_id": {"enum": enum([
            (1, "Created", "An incident report was opened."),
            (2, "Updated", "An existing incident report was amended."),
            (3, "Submitted", "The report was submitted for review."),
            (4, "Approved", "The report was approved by a supervisor."),
            (5, "Closed", "The incident was closed."),
            (6, "Reopened", "A closed incident was reopened."),
            (7, "Referred", "The incident was referred to a public safety agency or to the client."),
        ])},
        "incident_type_common": {"group": "primary", "requirement": "required"},
        "incident_type_internal": {"group": "primary", "requirement": "recommended"},
        "narrative": {"requirement": "optional"},
        "nibrs_offense_code": {"requirement": "optional"},
        "apco_incident_type": {"requirement": "optional"},
        "is_reportable": {"requirement": "optional"},
        "loss_amount": {"requirement": "optional"},
        "post": {"requirement": "optional"},
        "response_resource": {"requirement": "optional"},
        "disposition": {"requirement": "optional"},
    },
})

print("wrote extension to", ROOT)
for dirpath, _, files in os.walk(ROOT):
    for fn in sorted(files):
        print(" ", os.path.relpath(os.path.join(dirpath, fn), ROOT))
